steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-latest || true
        docker pull gcr.io/$PROJECT_ID/seeshell:master-builder-latest || true

        docker build -t gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-latest \
          --cache-from gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-latest \
          --cache-from gcr.io/$PROJECT_ID/seeshell:master-builder-latest \
          --target builder .
  - name: "gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-$SHORT_SHA"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        go test ./...
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-latest || true
        docker pull gcr.io/$PROJECT_ID/seeshell:master-builder-latest || true

        docker build -t gcr.io/$PROJECT_ID/seeshell:$SHORT_SHA \
          --cache-from gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-$SHORT_SHA \
          --cache-from gcr.io/$PROJECT_ID/seeshell:master-builder-latest .

        docker tag gcr.io/$PROJECT_ID/seeshell:$SHORT_SHA gcr.io/$PROJECT_ID/seeshell:latest
        docker push gcr.io/$PROJECT_ID/seeshell:latest
images:
  - "gcr.io/$PROJECT_ID/seeshell:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/seeshell:$BRANCH_NAME-builder-latest"